FileVersion = 1
Dependencies = {corlib = "*", Dimtoo = "*", Pile = "*", Pile_OpenGL = "*", Pile_SDL2 = "*", Pile_SoLoud = "*"}

[Project]
Name = "NecroCard"
TargetType = "BeefGUIApplication"
StartupObject = "Pile.Core"
Aliases = ["PileGame"]

[Platform.Windows]
IconFile = "$(WorkspaceDir)/assets/icon.ico"
Description = "Necro Card"
Comments = "A game made for the Wowie 3 game jam"
Company = "EinBurgbauer"
ProductVersion = "1.0"
